# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

# Mod Properties
mod_version=1.6.0
maven_group=com.github.telvarost
archives_base_name=MostlyModernRecipes

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=b1.7.3
yarn_mappings=b1.7.3+e0778a3
loader_version=0.16.10

# Dependencies and/or Helpful Development Mods
modmenu_version=1.8.5-beta.11
glass_networking_version=1.0.6
gcapi_version = 3.3.0+gen2
retrocommands_version = 0.6.0+gen2

# StationAPI Dependencies and/or Helpful Development Mods
stapi_version = 2.0.0-alpha.5.4+gen2
stapi_fast_intro_version=2.0.0
bhcreative_version = 0.4.10+gen2
alwaysmoreitems_version=1.5.3
spawneggs_version=1.11.0

# Added by babric2ornithe
biny_mappings = 9859f76
client_raven_build = 2
server_raven_build = 2
client_sparrow_build = 2
server_sparrow_build = 2
starac_version = 1.2.1+mcb1.7.3+gen2
